import type { SeedRecipe } from "./types";

export const filipinoMainDishes: SeedRecipe[] = [
  {
    slug: "chicken-adobo",
    title: "Classic Filipino Chicken Adobo",
    description:
      "Tender chicken simmered in soy sauce, vinegar, garlic, bay leaves, and black pepper until rich, savory, and flavorful.",
    prepMinutes: 20,
    cookMinutes: 45,
    servings: 4,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Pat the chicken dry and place it in a large bowl.",
      "Add soy sauce, garlic, and black pepper. Marinate for at least 20 minutes.",
      "Brown the chicken in cooking oil over medium heat.",
      "Add the vinegar, water, bay leaves, and brown sugar.",
      "Simmer covered for 30 minutes, then uncover and reduce the sauce before serving with rice.",
    ],
    ingredients: [
      {
        slug: "chicken-thighs",
        name: "Chicken Thighs",
        amount: 1,
        unit: "kilogram",
        note: "Bone-in or boneless",
      },
      {
        slug: "soy-sauce",
        name: "Soy Sauce",
        amount: 0.5,
        unit: "cup",
      },
      {
        slug: "white-vinegar",
        name: "White Vinegar",
        amount: 0.5,
        unit: "cup",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 8,
        unit: "cloves",
        note: "Lightly crushed",
      },
      {
        slug: "bay-leaves",
        name: "Bay Leaves",
        amount: 3,
        unit: "leaves",
      },
      {
        slug: "black-peppercorns",
        name: "Black Peppercorns",
        amount: 1,
        unit: "teaspoon",
      },
      {
        slug: "brown-sugar",
        name: "Brown Sugar",
        amount: 1,
        unit: "tablespoon",
      },
      {
        slug: "cooking-oil",
        name: "Cooking Oil",
        amount: 1,
        unit: "tablespoon",
      },
      {
        slug: "water",
        name: "Water",
        amount: 1,
        unit: "cup",
      },
    ],
    nutrition: {
      calories: 520,
      proteinG: 38,
      carbsG: 12,
      fatG: 34,
      fiberG: 1,
    },
  },
  {
    slug: "kare-kare",
    title: "Kare-Kare",
    description:
      "A rich Filipino peanut stew made with beef, vegetables, peanut butter, and a savory shrimp paste accompaniment.",
    prepMinutes: 30,
    cookMinutes: 120,
    servings: 6,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Boil the beef until tender, reserving the cooking broth.",
      "Sauté garlic and onion, then add annatto oil.",
      "Add peanut butter, ground peanuts, and beef broth.",
      "Add the tender beef and simmer until the sauce thickens.",
      "Blanch the vegetables separately and serve the stew with shrimp paste.",
    ],
    ingredients: [
      {
        slug: "beef-shank",
        name: "Beef Shank",
        amount: 1,
        unit: "kilogram",
        note: "Cut into pieces",
      },
      {
        slug: "peanut-butter",
        name: "Peanut Butter",
        amount: 1,
        unit: "cup",
      },
      {
        slug: "ground-peanuts",
        name: "Ground Peanuts",
        amount: 0.5,
        unit: "cup",
      },
      {
        slug: "annatto-seeds",
        name: "Annatto Seeds",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "eggplant",
        name: "Eggplant",
        amount: 2,
        unit: "pieces",
        note: "Sliced",
      },
      {
        slug: "bok-choy",
        name: "Bok Choy",
        amount: 2,
        unit: "cups",
      },
      {
        slug: "string-beans",
        name: "String Beans",
        amount: 2,
        unit: "cups",
      },
      {
        slug: "shrimp-paste",
        name: "Shrimp Paste",
        amount: 0.5,
        unit: "cup",
        note: "Serve on the side",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 5,
        unit: "cloves",
      },
      {
        slug: "onion",
        name: "Onion",
        amount: 1,
        unit: "piece",
      },
    ],
    nutrition: {
      calories: 590,
      proteinG: 39,
      carbsG: 24,
      fatG: 39,
      fiberG: 7,
    },
  },
  {
    slug: "beef-caldereta",
    title: "Beef Caldereta",
    description:
      "A hearty Filipino beef stew cooked with tomato sauce, liver spread, potatoes, carrots, and bell peppers.",
    prepMinutes: 25,
    cookMinutes: 105,
    servings: 6,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Season the beef and brown it in a heavy pot.",
      "Sauté garlic, onion, and tomato paste.",
      "Return the beef to the pot and add tomato sauce and broth.",
      "Simmer until the beef is tender.",
      "Add liver spread, potatoes, carrots, and peppers. Cook until the vegetables are tender.",
    ],
    ingredients: [
      {
        slug: "beef-chuck",
        name: "Beef Chuck",
        amount: 1,
        unit: "kilogram",
        note: "Cubed",
      },
      {
        slug: "tomato-sauce",
        name: "Tomato Sauce",
        amount: 2,
        unit: "cups",
      },
      {
        slug: "liver-spread",
        name: "Liver Spread",
        amount: 0.5,
        unit: "cup",
      },
      {
        slug: "potatoes",
        name: "Potatoes",
        amount: 3,
        unit: "pieces",
        note: "Cubed",
      },
      {
        slug: "carrots",
        name: "Carrots",
        amount: 2,
        unit: "pieces",
        note: "Sliced",
      },
      {
        slug: "bell-peppers",
        name: "Bell Peppers",
        amount: 2,
        unit: "pieces",
        note: "Sliced",
      },
      {
        slug: "tomato-paste",
        name: "Tomato Paste",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "beef-broth",
        name: "Beef Broth",
        amount: 3,
        unit: "cups",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 5,
        unit: "cloves",
      },
      {
        slug: "onion",
        name: "Onion",
        amount: 1,
        unit: "piece",
      },
    ],
    nutrition: {
      calories: 620,
      proteinG: 43,
      carbsG: 31,
      fatG: 38,
      fiberG: 6,
    },
  },
  {
    slug: "pork-menudo",
    title: "Pork Menudo",
    description:
      "A classic Filipino pork and liver stew with potatoes, carrots, bell peppers, tomato sauce, and raisins.",
    prepMinutes: 25,
    cookMinutes: 70,
    servings: 6,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Marinate the pork in soy sauce and calamansi juice.",
      "Brown the pork in a large pot.",
      "Sauté garlic and onion, then add tomato sauce.",
      "Return the pork and simmer until tender.",
      "Add liver, potatoes, carrots, peppers, and raisins. Cook until done.",
    ],
    ingredients: [
      {
        slug: "pork-shoulder",
        name: "Pork Shoulder",
        amount: 750,
        unit: "grams",
        note: "Cubed",
      },
      {
        slug: "pork-liver",
        name: "Pork Liver",
        amount: 250,
        unit: "grams",
        note: "Cubed",
      },
      {
        slug: "tomato-sauce",
        name: "Tomato Sauce",
        amount: 2,
        unit: "cups",
      },
      {
        slug: "potatoes",
        name: "Potatoes",
        amount: 2,
        unit: "pieces",
        note: "Cubed",
      },
      {
        slug: "carrots",
        name: "Carrots",
        amount: 2,
        unit: "pieces",
        note: "Cubed",
      },
      {
        slug: "bell-peppers",
        name: "Bell Peppers",
        amount: 1,
        unit: "piece",
      },
      {
        slug: "raisins",
        name: "Raisins",
        amount: 0.25,
        unit: "cup",
      },
      {
        slug: "soy-sauce",
        name: "Soy Sauce",
        amount: 3,
        unit: "tablespoons",
      },
      {
        slug: "calamansi-juice",
        name: "Calamansi Juice",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 5,
        unit: "cloves",
      },
    ],
    nutrition: {
      calories: 540,
      proteinG: 35,
      carbsG: 34,
      fatG: 28,
      fiberG: 5,
    },
  },
  {
    slug: "lechon-kawali",
    title: "Lechon Kawali",
    description:
      "Crispy deep-fried Filipino pork belly served with a savory vinegar dipping sauce.",
    prepMinutes: 15,
    cookMinutes: 100,
    servings: 5,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Place the pork belly in a pot with water, garlic, bay leaves, and salt.",
      "Simmer until the pork is tender.",
      "Remove the pork and allow it to cool completely.",
      "Pat the skin dry and fry until golden and crispy.",
      "Rest the pork, slice it, and serve with dipping sauce.",
    ],
    ingredients: [
      {
        slug: "pork-belly",
        name: "Pork Belly",
        amount: 1,
        unit: "kilogram",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 6,
        unit: "cloves",
      },
      {
        slug: "bay-leaves",
        name: "Bay Leaves",
        amount: 3,
        unit: "leaves",
      },
      {
        slug: "white-vinegar",
        name: "White Vinegar",
        amount: 0.5,
        unit: "cup",
        note: "For dipping sauce",
      },
      {
        slug: "salt",
        name: "Salt",
        amount: 1,
        unit: "tablespoon",
      },
      {
        slug: "black-peppercorns",
        name: "Black Peppercorns",
        amount: 1,
        unit: "teaspoon",
      },
      {
        slug: "cooking-oil",
        name: "Cooking Oil",
        amount: 4,
        unit: "cups",
        note: "For deep frying",
      },
    ],
    nutrition: {
      calories: 760,
      proteinG: 30,
      carbsG: 3,
      fatG: 70,
      fiberG: 0,
    },
  },
  {
    slug: "sisig",
    title: "Filipino Pork Sisig",
    description:
      "A sizzling Filipino dish made with chopped pork, onions, chili peppers, calamansi, and a savory soy dressing.",
    prepMinutes: 25,
    cookMinutes: 60,
    servings: 4,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Boil the pork face or pork belly until tender.",
      "Grill or pan-sear the pork until the edges become crisp.",
      "Chop the pork into small pieces.",
      "Sauté onion, garlic, and chili peppers.",
      "Add the chopped pork, soy sauce, and calamansi juice. Serve sizzling.",
    ],
    ingredients: [
      {
        slug: "pork-belly",
        name: "Pork Belly",
        amount: 750,
        unit: "grams",
      },
      {
        slug: "onion",
        name: "Onion",
        amount: 1,
        unit: "large",
        note: "Finely chopped",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 4,
        unit: "cloves",
      },
      {
        slug: "red-chili",
        name: "Red Chili",
        amount: 2,
        unit: "pieces",
        note: "Sliced",
      },
      {
        slug: "calamansi-juice",
        name: "Calamansi Juice",
        amount: 3,
        unit: "tablespoons",
      },
      {
        slug: "soy-sauce",
        name: "Soy Sauce",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "mayonnaise",
        name: "Mayonnaise",
        amount: 3,
        unit: "tablespoons",
      },
    ],
    nutrition: {
      calories: 610,
      proteinG: 32,
      carbsG: 9,
      fatG: 49,
      fiberG: 2,
    },
  },
  {
    slug: "bistek-tagalog",
    title: "Bistek Tagalog",
    description:
      "Thin slices of beef marinated in calamansi and soy sauce, then cooked with caramelized onions.",
    prepMinutes: 30,
    cookMinutes: 25,
    servings: 4,
    categorySlug: "main-dishes",
    categoryName: "Main Dishes",
    steps: [
      "Marinate the beef in calamansi juice, soy sauce, garlic, and pepper.",
      "Heat oil and sear the beef slices quickly on both sides.",
      "Remove the beef and sauté the onion rings.",
      "Return the beef to the pan and add the marinade.",
      "Simmer briefly and serve with steamed rice.",
    ],
    ingredients: [
      {
        slug: "beef-sirloin",
        name: "Beef Sirloin",
        amount: 700,
        unit: "grams",
        note: "Thinly sliced",
      },
      {
        slug: "calamansi-juice",
        name: "Calamansi Juice",
        amount: 0.25,
        unit: "cup",
      },
      {
        slug: "soy-sauce",
        name: "Soy Sauce",
        amount: 0.25,
        unit: "cup",
      },
      {
        slug: "onion",
        name: "Onion",
        amount: 2,
        unit: "large",
        note: "Sliced into rings",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 4,
        unit: "cloves",
      },
      {
        slug: "black-pepper",
        name: "Ground Black Pepper",
        amount: 1,
        unit: "teaspoon",
      },
      {
        slug: "cooking-oil",
        name: "Cooking Oil",
        amount: 2,
        unit: "tablespoons",
      },
    ],
    nutrition: {
      calories: 460,
      proteinG: 42,
      carbsG: 13,
      fatG: 27,
      fiberG: 2,
    },
  },
];