import type { SeedRecipe } from "./types";

export const filipinoSoups: SeedRecipe[] = [
  {
    slug: "sinigang-na-baboy",
    title: "Sinigang na Baboy",
    description:
      "A comforting Filipino sour soup made with pork, tamarind, tomatoes, radish, green beans, and leafy vegetables.",
    prepMinutes: 20,
    cookMinutes: 75,
    servings: 6,
    categorySlug: "soups",
    categoryName: "Soups",
    steps: [
      "Place the pork, onion, tomatoes, and water in a large pot.",
      "Bring the mixture to a boil and remove any foam from the surface.",
      "Lower the heat and simmer until the pork becomes tender.",
      "Add the tamarind soup base, radish, eggplant, and green beans.",
      "Add the water spinach and season with fish sauce before serving hot.",
    ],
    ingredients: [
      {
        slug: "pork-belly",
        name: "Pork Belly",
        amount: 1,
        unit: "kilogram",
        note: "Cut into serving pieces",
      },
      {
        slug: "onion",
        name: "Onion",
        amount: 1,
        unit: "large",
        note: "Quartered",
      },
      {
        slug: "tomatoes",
        name: "Tomatoes",
        amount: 2,
        unit: "pieces",
        note: "Quartered",
      },
      {
        slug: "tamarind-soup-base",
        name: "Tamarind Soup Base",
        amount: 1,
        unit: "packet",
      },
      {
        slug: "radish",
        name: "White Radish",
        amount: 1,
        unit: "medium",
        note: "Sliced",
      },
      {
        slug: "eggplant",
        name: "Eggplant",
        amount: 1,
        unit: "piece",
        note: "Sliced",
      },
      {
        slug: "green-beans",
        name: "Green Beans",
        amount: 150,
        unit: "grams",
      },
      {
        slug: "water-spinach",
        name: "Water Spinach",
        amount: 2,
        unit: "cups",
      },
      {
        slug: "fish-sauce",
        name: "Fish Sauce",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "water",
        name: "Water",
        amount: 8,
        unit: "cups",
      },
    ],
    nutrition: {
      calories: 410,
      proteinG: 31,
      carbsG: 18,
      fatG: 24,
      fiberG: 5,
    },
  },
  {
    slug: "chicken-tinola",
    title: "Chicken Tinola",
    description:
      "A light Filipino ginger chicken soup with green papaya, chili leaves, garlic, and fish sauce.",
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 4,
    categorySlug: "soups",
    categoryName: "Soups",
    steps: [
      "Heat oil in a pot and sauté garlic, onion, and ginger.",
      "Add the chicken pieces and cook until lightly browned.",
      "Pour in the water and bring the soup to a boil.",
      "Simmer until the chicken is tender.",
      "Add green papaya and chili leaves, then season with fish sauce.",
    ],
    ingredients: [
      {
        slug: "whole-chicken",
        name: "Whole Chicken",
        amount: 1,
        unit: "kilogram",
        note: "Cut into pieces",
      },
      {
        slug: "ginger",
        name: "Fresh Ginger",
        amount: 50,
        unit: "grams",
        note: "Sliced",
      },
      {
        slug: "onion",
        name: "Onion",
        amount: 1,
        unit: "piece",
        note: "Sliced",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 4,
        unit: "cloves",
      },
      {
        slug: "green-papaya",
        name: "Green Papaya",
        amount: 2,
        unit: "cups",
        note: "Peeled and sliced",
      },
      {
        slug: "chili-leaves",
        name: "Chili Leaves",
        amount: 2,
        unit: "cups",
      },
      {
        slug: "fish-sauce",
        name: "Fish Sauce",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "cooking-oil",
        name: "Cooking Oil",
        amount: 1,
        unit: "tablespoon",
      },
      {
        slug: "water",
        name: "Water",
        amount: 7,
        unit: "cups",
      },
    ],
    nutrition: {
      calories: 330,
      proteinG: 35,
      carbsG: 14,
      fatG: 15,
      fiberG: 3,
    },
  },
];