import type { SeedRecipe } from "./types";

export const filipinoNoodles: SeedRecipe[] = [
  {
    slug: "pancit-canton",
    title: "Pancit Canton",
    description:
      "Stir-fried Filipino noodles with chicken, shrimp, cabbage, carrots, green beans, and savory soy seasoning.",
    prepMinutes: 25,
    cookMinutes: 25,
    servings: 5,
    categorySlug: "noodles",
    categoryName: "Noodles",
    steps: [
      "Soak or prepare the noodles according to the package instructions.",
      "Sauté garlic and onion in a large wok.",
      "Cook the chicken and shrimp until fully done.",
      "Add the vegetables and stir-fry until slightly tender.",
      "Add the noodles, soy sauce, oyster sauce, and broth. Toss until combined.",
    ],
    ingredients: [
      {
        slug: "flour-noodles",
        name: "Flour Noodles",
        amount: 500,
        unit: "grams",
      },
      {
        slug: "chicken-breast",
        name: "Chicken Breast",
        amount: 300,
        unit: "grams",
        note: "Thinly sliced",
      },
      {
        slug: "shrimp",
        name: "Shrimp",
        amount: 250,
        unit: "grams",
        note: "Peeled",
      },
      {
        slug: "cabbage",
        name: "Cabbage",
        amount: 2,
        unit: "cups",
        note: "Shredded",
      },
      {
        slug: "carrots",
        name: "Carrots",
        amount: 1,
        unit: "large",
        note: "Julienned",
      },
      {
        slug: "green-beans",
        name: "Green Beans",
        amount: 1,
        unit: "cup",
        note: "Sliced",
      },
      {
        slug: "soy-sauce",
        name: "Soy Sauce",
        amount: 3,
        unit: "tablespoons",
      },
      {
        slug: "oyster-sauce",
        name: "Oyster Sauce",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "chicken-broth",
        name: "Chicken Broth",
        amount: 1,
        unit: "cup",
      },
      {
        slug: "cooking-oil",
        name: "Cooking Oil",
        amount: 2,
        unit: "tablespoons",
      },
    ],
    nutrition: {
      calories: 480,
      proteinG: 27,
      carbsG: 68,
      fatG: 12,
      fiberG: 6,
    },
  },
  {
    slug: "pancit-palabok",
    title: "Pancit Palabok",
    description:
      "Filipino rice noodles covered with shrimp sauce and topped with shrimp, egg, pork, and crispy garlic.",
    prepMinutes: 35,
    cookMinutes: 40,
    servings: 5,
    categorySlug: "noodles",
    categoryName: "Noodles",
    steps: [
      "Soak and cook the rice noodles until tender.",
      "Prepare the shrimp stock using shrimp shells.",
      "Thicken the stock with cornstarch and annatto oil.",
      "Top the noodles with the shrimp sauce.",
      "Garnish with shrimp, boiled egg, pork, spring onion, and fried garlic.",
    ],
    ingredients: [
      {
        slug: "rice-noodles",
        name: "Rice Noodles",
        amount: 500,
        unit: "grams",
      },
      {
        slug: "shrimp",
        name: "Shrimp",
        amount: 350,
        unit: "grams",
      },
      {
        slug: "ground-pork",
        name: "Ground Pork",
        amount: 250,
        unit: "grams",
      },
      {
        slug: "annatto-seeds",
        name: "Annatto Seeds",
        amount: 2,
        unit: "tablespoons",
      },
      {
        slug: "cornstarch",
        name: "Cornstarch",
        amount: 3,
        unit: "tablespoons",
      },
      {
        slug: "egg",
        name: "Egg",
        amount: 3,
        unit: "pieces",
        note: "Hard-boiled",
      },
      {
        slug: "garlic",
        name: "Garlic",
        amount: 6,
        unit: "cloves",
        note: "Fried until crisp",
      },
      {
        slug: "fish-sauce",
        name: "Fish Sauce",
        amount: 2,
        unit: "tablespoons",
      },
    ],
    nutrition: {
      calories: 510,
      proteinG: 28,
      carbsG: 71,
      fatG: 13,
      fiberG: 3,
    },
  },
];